const usps = [
  {
    title: "AI Generates Human-Like Emails",
    description: "Our AI understands context, tone, and intent to produce emails that sound natural, professional, and persuasive every time.",
    icon: "🤖",
  },
  {
    title: "Works in Seconds",
    description: "No waiting. Enter a few details and generate a polished email instantly, saving hours of writing time each week.",
    icon: "⚡",
  },
  {
    title: "Privacy-Focused & Secure",
    description: "We never store your emails or personal data. Your content is private and fully secure, giving you peace of mind.",
    icon: "🔒",
  },
  {
    title: "No Prompts or Complicated Setup",
    description: "Simple, clean interface. Just provide the basics and get professional emails with a single click.",
    icon: "🛠️",
  },
  {
    title: "Boosts Reply Rates",
    description: "Emails generated by Serenedale are structured to get noticed, increasing response rates and engagement.",
    icon: "📈",
  },
  {
    title: "Customizable Tones",
    description: "Choose between professional, friendly, or persuasive tones to fit any situation or audience.",
    icon: "🎨",
  },
];

const WhyChooseUs = () => {
  return (
    <section className="py-32 bg-gray-950 text-white px-6">
      <div className="max-w-7xl mx-auto text-center">

        {/* Header */}
        <div className="mb-20 max-w-3xl mx-auto">
          <h2 className="text-4xl md:text-5xl font-bold mb-6">Why Choose Serenedale? 💜</h2>
          <p className="text-gray-400 text-lg">
            Serenedale is not just another email generator. Every feature is designed
            to save you time, increase your impact, and keep your communication private.
          </p>
        </div>

        {/* USP Grid */}
        <div className="grid md:grid-cols-2 gap-12">
          {usps.map((item, index) => (
            <div
              key={index}
              className="bg-white/5 border border-white/10 p-8 rounded-2xl shadow-lg hover:bg-white/10 transition duration-300"
            >
              <div className="text-4xl mb-4">{item.icon}</div>
              <h3 className="text-2xl font-semibold mb-3">{item.title}</h3>
              <p className="text-gray-300 leading-relaxed">{item.description}</p>
            </div>
          ))}
        </div>

        {/* Extra Notes / Highlights */}
        <div className="mt-32 max-w-4xl mx-auto text-left space-y-6 text-gray-300">
          <p>✨ Trusted by thousands of professionals, students, and teams worldwide.</p>
          <p>📩 Works for any email type: cold emails, follow-ups, apologies, proposals, or outreach.</p>
          <p>🧠 Continuously improving AI — smarter suggestions every time you use it.</p>
          <p>🌍 Compatible across devices — desktop, mobile, or tablet.</p>
          <p>🚀 Saves hours of writing time weekly, helping you focus on what matters most.</p>
        </div>

        {/* Call To Action */}
        <div className="mt-20 text-center">
          <h3 className="text-3xl font-bold mb-4">Start Writing Smarter Emails Today</h3>
          <p className="text-gray-400 mb-8">
            Experience the power of AI-generated emails and see the difference for yourself.
          </p>
          <button className="px-12 py-4 rounded-xl bg-purple-600 hover:bg-purple-700 transition font-semibold text-lg">
            Generate My First Email 🚀
          </button>
        </div>

      </div>
    </section>
  );
};

export default WhyChooseUs;
